# Generated by Django 4.1.1 on 2023-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_1app', '0002_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('timings', models.TimeField(max_length=50)),
                ('starting_date', models.DateField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('trainer_name', models.CharField(max_length=50)),
            ],
        ),
    ]
