# Generated by Django 4.1.1 on 2022-10-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('iname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('assigment1', models.IntegerField()),
                ('assigment2', models.IntegerField()),
                ('assigment3', models.IntegerField()),
                ('assigment4', models.IntegerField()),
            ],
        ),
    ]
